name: Build website

on:
  workflow_run:
    workflows: ["Make database"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install datasette sqlite-utils
        datasette install datasette-publish-vercel
    - name: Download database
      run: curl --fail -OL https://github.com/cbeauhilton/ash-db/releases/download/database/abstracts.db
    - name: Shrink db for Vercel
      run: |-
        sqlite-utils ash-db/abstracts.db "SELECT doi, article_title, article_date, session_type, topics, author_names, author_affiliations, first_author_latitude, first_author_longitude from abstracts WHERE is_scraped=1 LIMIT 40000" | sqlite-utils insert ash-db/abstracts_small.db abstracts - --pk=doi
        sqlite-utils enable-counts ash-db/abstracts_small.db
        sqlite-utils enable-fts ash-db/abstracts_small.db abstracts article_title author_names author_affiliations
        sqlite-utils optimize ash-db/abstracts_small.db
    - name: Soundness check
      run: |-
        datasette abstracts_small.db --get / | grep "abstracts"
    - name: Replace metadata.json
      # Vercel does not yet support Python >3.6, which is req by remote-metadata
      run: cat remote-metadata.yaml > metadata.yaml
    - name: Deploy Datasette using Vercel
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish vercel abstracts_small.db \
          --setting default_page_size 10 \
          --token $NOW_TOKEN \
          --project ash-abstracts \
          --static static:static \
          --metadata metadata.yaml \
          --install datasette-json-html \
          --install datasette-cluster-map \
          --public
    - name: Download scraping database
      run: curl --fail -OL https://github.com/cbeauhilton/ash-db/releases/download/database/unscraped.db
    - name: Soundness check
      run: |-
        datasette unscraped.db --get / | grep "unscraped"
    - name: Replace metadata.json
      # Vercel does not yet support Python >3.6, which is req by remote-metadata
      run: cat remote-metadata.yaml > metadata.yaml
    - name: Deploy Datasette using Vercel
      env:
        NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
      run: |-
        datasette publish vercel unscraped.db \
          --setting default_page_size 500 \
          --token $NOW_TOKEN \
          --project ash-unscraped \
          --static static:static \
          --metadata metadata.yaml \
          --install datasette-json-html \
          --install datasette-cluster-map \
          --public
