name: Scrape DOI

on:
  push:
    branches:
    - main
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    uses: cbeauhilton/ash-abstracts/.github/workflows/scraper.yml@main
    with:
      scraper: dois
      commit_message: DOI
    secrets:
      push_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
