name: Make database

on:
  workflow_run:
    workflows: ["Scrape DOI", "Scrape abstracts"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
    - name: Checkout ash-db
      uses: actions/checkout@v2
      with:
        repository: cbeauhilton/ash-db
        path: ash-db
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Checkout ash-files
      uses: actions/checkout@v2
      with:
        repository: cbeauhilton/ash-files
        path: ash-files
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlite-utils
    - name: Make databases
      run: |-
        git config --global user.name "db bot"       
        git config --global user.email "actions@users.noreply.github.com"
        find ash-files/doi_json -maxdepth 1 -type f -name \*.json -exec cat {} + | jq -s . > db.json
        sqlite-utils insert ash-db/abstracts.db abstracts db.json --pk=doi --alter
        sqlite-utils enable-counts ash-db/abstracts_full.db
        sqlite-utils enable-fts ash-db/abstracts_full.db abstracts article_title abstract_text author_names author_affiliations
        sqlite-utils optimize ash-db/abstracts_full.db
        jq 'del(.abstract_text)' db.json > db.json
        sqlite-utils insert ash-db/abstracts.db abstracts db.json --pk=doi --alter
        sqlite-utils enable-counts ash-db/abstracts.db
        sqlite-utils enable-fts ash-db/abstracts.db abstracts article_title author_names author_affiliations
        sqlite-utils optimize ash-db/abstracts.db
    - name: Echo current db info
      run: |-
        cd ash-db
        echo ""
        echo "Current number of items in db:"
        sqlite-utils abstracts.db "SELECT count(*) from abstracts"
        echo ""
        echo "Current number of scraped items in db:"
        sqlite-utils abstracts.db "SELECT count(*) from abstracts WHERE is_scraped = 1"
        echo ""
        echo "Current start url page number:"
        sqlite-utils abstracts.db "SELECT MAX(start_url_page_num) from abstracts"
    - name: Update readme
      run: |-
        cd ash-db
        timestamp=$(date -u)
        echo "Release last updated: ${timestamp} . " > README.md
        echo "" >> README.md
        echo "Available [here](https://github.com/cbeauhilton/ash-db/releases)." >> README.md
        git remote prune origin
        git add README.md
        git commit --amend --no-edit
        git push --force
    - name: Upload to releases
      uses: softprops/action-gh-release@v1
      with:
        repository: cbeauhilton/ash-db
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_FOR_PUSH }}
        tag_name: "database"
        files: |
          ash-db/abstracts.db
          ash-db/abstracts_full.db
