name: Scrape DOI from ASH website

on:
  push:
    branches:
    - main
  schedule:
    - cron: '1 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Scrape DOI
      if: |-
        contains(github.event.head_commit.message, 'DOI') || (github.event_name == 'schedule')
      run: |-
        export DETA_TOKEN_ASH=${{ secrets.DETA_TOKEN_ASH }}
        export DETA_ID_ASH=${{ secrets.DETA_ID_ASH }}
        cd scrape_ash/scrape_ash/
        cat gha_settings.py > settings.py
        scrapy crawl dois
